Codereview
maab2198/genesis_FE_HW_1 pull request #1
Opened 2021-12-26 16:44 UTC by maab2198

2021-12-26 18:30 UTC, olharums requested changes
В цілому все добре, виправити деякі невеличкі хиби.

2021-12-26 18:30 UTC, olharums commented on package.json
>      "start": "react-scripts start",
`"linter": "eslint 'src/**/*.{js,jsx}'"` - вибиває помилку. Фікситься прибиранням одинарних лапок.

2021-12-26 18:30 UTC, olharums commented on src/App.jsx
> +
Пропоную не залишати закоментований код

2021-12-26 18:30 UTC, olharums commented on src/components/Layout/Layout.module.css
> +}
Пропоную не залишати закоментований код

2021-12-26 18:30 UTC, olharums commented on src/components/Trend/HashtagList.jsx
> +  }
`hashtags.length === 0` можна скоротити до `!hashtags.length`, але це справа смаку

2021-12-26 18:30 UTC, olharums commented on src/components/Trend/TrendItem.jsx
> +        <HashtagList hashtags={item.hashtags} />
`item.hashtags.lendth` => мабуть `item.hashtags.len`**g**`th` ?

2021-12-26 18:30 UTC, olharums commented on src/components/Trend/TrendList.jsx
> +  const {
Не розумію, яку інформацію несе коментар

2021-12-26 18:30 UTC, olharums commented on src/components/Trend/TrendList.jsx
> +          ))}
Пропоную змінити код таким чином:
додаємо окремий `if `на перевірку помилки, який повертає  `{error.message}` (або ж компонент Error з UI/Error.jsx)
далі пишемо "основний" `return `без перевірок, який повертає `trendingFeed.map(...)`

2021-12-26 18:30 UTC, olharums commented on src/components/Trend/TrendList.jsx
> +          ))}
Навіщо в TrendItem передаємо окремо item.id, якщо ми водночас передаємо цілий item?

2021-12-26 18:30 UTC, olharums commented on src/components/User/UserFeed.jsx
> +    </ul>
Здається, перевірка !error зайва, адже ми цю умову перевірили вже раніше

2021-12-26 18:30 UTC, olharums commented on src/components/User/UserFeedItem.jsx
> +const UserFeedItem = ({ item }) => (
Яку інформацію несе коментар?

2021-12-26 18:30 UTC, olharums commented on src/index.css
> +  --primary-color: #ffe66d;
Коментарі важливі?

2021-12-26 18:30 UTC, olharums commented on src/lib/api.js
> +  }
За бажанням: `trendingFeed.length === 0 ` => `!trendingFeed.length`

2021-12-26 18:30 UTC, olharums commented on src/pages/UserPage.jsx
> +
Пропоную: 
```
const params = useParams()
const { userId } = params
```
скоротити до `const { userId } = useParams()`

2021-12-30 15:55 UTC, helmax-y requested changes

2021-12-30 15:55 UTC, helmax-y commented on README.md
> +Get User Feed didn't work properly, so I used Get Trending Feed instead
хороше readme, мені подобається
із скрінами на випадок що сервер вертатиме 403 і я не зможу заранити)

2021-12-30 15:55 UTC, helmax-y commented on src/store/ThemeProvider.js
> +  const [themeState, setTheme] = useState(defaultTheme)
а частинка `State` тут точно треба? зазвичай перше і друге значення в масиві іменуються ідентично, лиш додається префікс `set`

2021-12-30 15:55 UTC, helmax-y commented on src/store/theme-context.js
> +export default ThemeContext
а чому цей файл названо не через camelCase?

2021-12-30 15:55 UTC, helmax-y commented on src/store/theme-context.js
> +const ThemeContext = React.createContext(defaultTheme)
`createContext` слід заімпортити зверху окремо. в інших компонентах ти імпортиш `useEffect` саме так

`Practice consistency` принцип

2021-12-30 15:55 UTC, helmax-y commented on src/store/ThemeProvider.js
> +    <ThemeContext.Provider value={React.useMemo(themeContext)}>
1. `useMemo` треба заімпортити окремо
2. а `useMemo` точно працює таким чином? мені здається він приймає колбек. також має бути dependancy array

2021-12-30 15:55 UTC, helmax-y commented on src/store/ThemeProvider.js
> +    <ThemeContext.Provider value={React.useMemo(themeContext)}>
мені здається не дуже влучний неймінг. і компонент називається ThemeContext, і у value теж прокидується themeContext

2021-12-30 15:55 UTC, helmax-y commented on src/hooks/use-http.js
> +export default useHttp
знову файл називається не так само як хук. camelCase

2021-12-30 15:55 UTC, helmax-y commented on src/App.jsx
> +import UserPage from "./pages/UserPage"
не критично, але є прикольна практика віддляти імпорт бібліотек від імпорту файлів проекту. тоді трохи легше по тим імпортам орієнтуватись

2021-12-30 15:55 UTC, helmax-y commented on src/pages/TrendPage.jsx
> +import Layout from "../components/Layout/Layout"
дивись, в тебе в шляху Layout, і знову Layout. можливо тоді назвати сам файл `index.jsx`?

2021-12-30 15:55 UTC, helmax-y commented on src/components/Theme/Theme.js
> +export default Theme
чому файл не jsx?

2021-12-30 15:55 UTC, helmax-y commented on src/components/Theme/Theme.js
> +  const themeCtx = useContext(ThemeContext)
щоб уникнути цієї проблеми неймінгу, можна одразу деструктурувати об'єкт

```suggestion
  const { name, toggleTheme } = useContext(ThemeContext)
```

2021-12-30 15:55 UTC, helmax-y commented on src/components/Trend/TrendList.jsx
> +        {status !== "pending" &&
а хіба може бути в цьому місці статус pending. вже ж раніше зроблено перевірку на pending

2021-12-30 15:55 UTC, helmax-y commented on src/components/UI/SectionWrapper.module.css
> +@media (min-width: 640px) {
точки переходу в тебе всюди однакові. можна ці цифри - 640px i 1024px - винести в константу

2021-12-30 15:55 UTC, helmax-y commented on src/hooks/use-http.js
> +        const responseData = await requestFunction(requestData)
після присвоєння треба пустий рядок

2021-12-30 15:55 UTC, helmax-y commented on src/components/User/UserFeedItem.jsx
> +const UserFeedItem = ({ item }) => (
зазвичай назва компоненту і має говорити про те що тут відбувається
я б уникав цих додаткових коментів

2021-12-30 15:55 UTC, helmax-y commented on src/components/User/UserInfo.jsx
> +    data: userInfo,
і компонент UserInfo, і дані userInfo
в return `userInfo` написано 5 разів. цього можна легко уникнути

```suggestion
    data: { stats, user },
```

2021-12-30 15:55 UTC, helmax-y commented on src/components/Trend/Author.jsx
> +    <Link className={styles.author_names} to={`/user/${author.name}`} replace>
повсюду в іменах класів дефіс, а тут underscore

2021-12-30 15:55 UTC, helmax-y commented on src/components/Trend/Author.jsx
> +    <Link className={styles.author_names} to={`/user/${author.name}`} replace>
якщо це bem, то має бути подвійний underscore

2021-12-30 15:55 UTC, helmax-y commented on src/components/UI/Error.jsx
> +  return <h2>{message}</h2>
тут треба трохи більше простору. перед return варто лишати пустий рядок

2021-12-30 15:55 UTC, helmax-y commented on src/components/Trend/TrendItem.jsx
> +        </p>
тут повторення. можна сформувати масив і скористатись `map`

2022-01-05 16:35 UTC, maab2198 commented on src/pages/TrendPage.jsx
> +import Layout from "../components/Layout/Layout"
мені не подобається ця практика ))

2022-01-05 16:39 UTC, maab2198 commented on src/hooks/use-http.js
> +export default useHttp
-

2022-01-05 16:39 UTC, maab2198 commented on src/store/theme-context.js
> +export default ThemeContext
-

2022-01-05 16:40 UTC, maab2198 commented on src/components/User/UserFeedItem.jsx
> +const UserFeedItem = ({ item }) => (
дякую, вже прибрала, це не очевидно, але він був про те що з тега <track> треба прибрати заглушку )))))

2022-01-05 17:00 UTC, maab2198 commented on src/components/Trend/TrendList.jsx
> +  const {
я вже теж )

2022-01-05 17:02 UTC, maab2198 commented on src/components/Trend/TrendItem.jsx
> +        </p>
Так, але в даному випадку позиція цих елементів в дом може змінитися, тому я вирішила зробити таким чином

2022-01-05 18:19 UTC, maab2198 commented on src/components/User/UserInfo.jsx
> +    data: userInfo,
звучало красиво, но нужно еще подумать

2022-01-31 16:22 UTC, closed without merging